import { NextPage } from 'next';
import Head from 'next/head';
import * as S from "../styles/styles"
import styled from 'styled-components';
import { CardEmotion } from '../components/CardEmotion';

const CircleIndicator: NextPage = () => {
  const Layout = styled.div`
    width: 100%;
    overflow-x: hidden;
    //position: relative;
  `;
  return (
    <>
      
      
      <Layout>
        <Head>
          <title>Institucional | ConsultPage</title>
          <meta name="description" content="Generated by created next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <S.Container>
          <CardEmotion />
        </S.Container>
      </Layout>
    </>
  );
};

export default CircleIndicator;
